/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from 'ethers'
import type { Signer, ContractDeployTransaction, ContractRunner } from 'ethers'
import type { NonPayableOverrides } from '../../common'
import type {
  FlipMoodNft,
  FlipMoodNftInterface,
} from '../../Interactions.s.sol/FlipMoodNft'

const _abi = [
  {
    type: 'function',
    name: 'IS_SCRIPT',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TOKEN_ID_TO_FLIP',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'flipMoodNft',
    inputs: [
      {
        name: 'moodNftAddress',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'run',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const

const _bytecode =
  '0x6080604052600c805462ff00ff19166201000117905534801561002157600080fd5b50610325806100316000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80638184b5ef14610051578063c040622614610066578063de37670f1461006e578063f8ccbf4714610089575b600080fd5b61006461005f3660046102ae565b6100ac565b005b6100646101f5565b610076600081565b6040519081526020015b60405180910390f35b600c5461009c9062010000900460ff1681565b6040519015158152602001610080565b7f885cb69240a935d632d79c317109709ecfa91a80626ff3989d68f67f5b1dd12d60001c6001600160a01b0316637fb5297f6040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561010a57600080fd5b505af115801561011e573d6000803e3d6000fd5b505060405163060d0a3d60e51b8152600060048201526001600160a01b038416925063c1a147a09150602401600060405180830381600087803b15801561016457600080fd5b505af1158015610178573d6000803e3d6000fd5b505050507f885cb69240a935d632d79c317109709ecfa91a80626ff3989d68f67f5b1dd12d60001c6001600160a01b03166376eadd366040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156101da57600080fd5b505af11580156101ee573d6000803e3d6000fd5b5050505050565b6040805163e374cdf160e01b815260048101919091526007604482015266135bdbd913999d60ca1b606482015246602482015260009073__$afaf3cb9b6fed785cfa99ccefb3a7db4f8$__9063e374cdf190608401602060405180830381865af4158015610267573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061028b91906102d2565b9050610296816100ac565b50565b6001600160a01b038116811461029657600080fd5b6000602082840312156102c057600080fd5b81356102cb81610299565b9392505050565b6000602082840312156102e457600080fd5b81516102cb8161029956fea264697066735822122069738156ee9d7e0d195348faa3ef7e5341345931f27d34d9cd4a047db55ac2a764736f6c63430008140033'

type FlipMoodNftConstructorParams =
  | [linkLibraryAddresses: FlipMoodNftLibraryAddresses, signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>

const isSuperArgs = (
  xs: FlipMoodNftConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => {
  return (
    typeof xs[0] === 'string' ||
    (Array.isArray as (arg: any) => arg is readonly any[])(xs[0]) ||
    '_isInterface' in xs[0]
  )
}

export class FlipMoodNft__factory extends ContractFactory {
  constructor(...args: FlipMoodNftConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args)
    } else {
      const [linkLibraryAddresses, signer] = args
      super(
        _abi,
        FlipMoodNft__factory.linkBytecode(linkLibraryAddresses),
        signer
      )
    }
  }

  static linkBytecode(
    linkLibraryAddresses: FlipMoodNftLibraryAddresses
  ): string {
    let linkedBytecode = _bytecode

    linkedBytecode = linkedBytecode.replace(
      new RegExp('__\\$afaf3cb9b6fed785cfa99ccefb3a7db4f8\\$__', 'g'),
      linkLibraryAddresses['lib/foundry-devops/src/DevOpsTools.sol:DevOpsTools']
        .replace(/^0x/, '')
        .toLowerCase()
    )

    return linkedBytecode
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {})
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FlipMoodNft & {
        deploymentTransaction(): ContractTransactionResponse
      }
    >
  }
  override connect(runner: ContractRunner | null): FlipMoodNft__factory {
    return super.connect(runner) as FlipMoodNft__factory
  }

  static readonly bytecode = _bytecode
  static readonly abi = _abi
  static createInterface(): FlipMoodNftInterface {
    return new Interface(_abi) as FlipMoodNftInterface
  }
  static connect(address: string, runner?: ContractRunner | null): FlipMoodNft {
    return new Contract(address, _abi, runner) as unknown as FlipMoodNft
  }
}

export interface FlipMoodNftLibraryAddresses {
  ['lib/foundry-devops/src/DevOpsTools.sol:DevOpsTools']: string
}
