/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from 'ethers'
import type { Signer, ContractDeployTransaction, ContractRunner } from 'ethers'
import type { NonPayableOverrides } from '../../common'
import type {
  MintDynamicNft,
  MintDynamicNftInterface,
} from '../../Interactions.s.sol/MintDynamicNft'

const _abi = [
  {
    type: 'function',
    name: 'IS_SCRIPT',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mintNftOnContract',
    inputs: [
      {
        name: 'dynamicNftAddress',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'run',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const

const _bytecode =
  '0x6080604052600c805462ff00ff19166201000117905534801561002157600080fd5b506102ff806100316000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063c040622614610046578063ddd6879514610050578063f8ccbf4714610063575b600080fd5b61004e61008a565b005b61004e61005e366004610288565b610131565b600c546100769062010000900460ff1681565b604051901515815260200160405180910390f35b6040805163e374cdf160e01b81526004810191909152600a604482015269111e5b985b5a58d3999d60b21b606482015246602482015260009073__$afaf3cb9b6fed785cfa99ccefb3a7db4f8$__9063e374cdf190608401602060405180830381865af41580156100ff573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061012391906102ac565b905061012e81610131565b50565b7f885cb69240a935d632d79c317109709ecfa91a80626ff3989d68f67f5b1dd12d60001c6001600160a01b0316637fb5297f6040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561018f57600080fd5b505af11580156101a3573d6000803e3d6000fd5b50505050806001600160a01b031663c2229fea6040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156101e257600080fd5b505af11580156101f6573d6000803e3d6000fd5b505050507f885cb69240a935d632d79c317109709ecfa91a80626ff3989d68f67f5b1dd12d60001c6001600160a01b03166376eadd366040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561025857600080fd5b505af115801561026c573d6000803e3d6000fd5b5050505050565b6001600160a01b038116811461012e57600080fd5b60006020828403121561029a57600080fd5b81356102a581610273565b9392505050565b6000602082840312156102be57600080fd5b81516102a58161027356fea2646970667358221220dbbd9d87a47822e43eb6fb538f9d372678f1cedf59d16a5b71481fee0cfa165164736f6c63430008140033'

type MintDynamicNftConstructorParams =
  | [linkLibraryAddresses: MintDynamicNftLibraryAddresses, signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>

const isSuperArgs = (
  xs: MintDynamicNftConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => {
  return (
    typeof xs[0] === 'string' ||
    (Array.isArray as (arg: any) => arg is readonly any[])(xs[0]) ||
    '_isInterface' in xs[0]
  )
}

export class MintDynamicNft__factory extends ContractFactory {
  constructor(...args: MintDynamicNftConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args)
    } else {
      const [linkLibraryAddresses, signer] = args
      super(
        _abi,
        MintDynamicNft__factory.linkBytecode(linkLibraryAddresses),
        signer
      )
    }
  }

  static linkBytecode(
    linkLibraryAddresses: MintDynamicNftLibraryAddresses
  ): string {
    let linkedBytecode = _bytecode

    linkedBytecode = linkedBytecode.replace(
      new RegExp('__\\$afaf3cb9b6fed785cfa99ccefb3a7db4f8\\$__', 'g'),
      linkLibraryAddresses['lib/foundry-devops/src/DevOpsTools.sol:DevOpsTools']
        .replace(/^0x/, '')
        .toLowerCase()
    )

    return linkedBytecode
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {})
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MintDynamicNft & {
        deploymentTransaction(): ContractTransactionResponse
      }
    >
  }
  override connect(runner: ContractRunner | null): MintDynamicNft__factory {
    return super.connect(runner) as MintDynamicNft__factory
  }

  static readonly bytecode = _bytecode
  static readonly abi = _abi
  static createInterface(): MintDynamicNftInterface {
    return new Interface(_abi) as MintDynamicNftInterface
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MintDynamicNft {
    return new Contract(address, _abi, runner) as unknown as MintDynamicNft
  }
}

export interface MintDynamicNftLibraryAddresses {
  ['lib/foundry-devops/src/DevOpsTools.sol:DevOpsTools']: string
}
