/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers'
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../common'

export interface DeployMoodNftInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'DEFAULT_ANVIL_PRIVATE_KEY'
      | 'IS_SCRIPT'
      | 'deployerKey'
      | 'run'
      | 'svgToImageURI'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'DEFAULT_ANVIL_PRIVATE_KEY',
    values?: undefined
  ): string
  encodeFunctionData(functionFragment: 'IS_SCRIPT', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'deployerKey',
    values?: undefined
  ): string
  encodeFunctionData(functionFragment: 'run', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'svgToImageURI',
    values: [string]
  ): string

  decodeFunctionResult(
    functionFragment: 'DEFAULT_ANVIL_PRIVATE_KEY',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'IS_SCRIPT', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'deployerKey', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'run', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'svgToImageURI',
    data: BytesLike
  ): Result
}

export interface DeployMoodNft extends BaseContract {
  connect(runner?: ContractRunner | null): DeployMoodNft
  waitForDeployment(): Promise<this>

  interface: DeployMoodNftInterface

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>

  DEFAULT_ANVIL_PRIVATE_KEY: TypedContractMethod<[], [bigint], 'view'>

  IS_SCRIPT: TypedContractMethod<[], [boolean], 'view'>

  deployerKey: TypedContractMethod<[], [bigint], 'view'>

  run: TypedContractMethod<[], [string], 'nonpayable'>

  svgToImageURI: TypedContractMethod<[svg: string], [string], 'view'>

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T

  getFunction(
    nameOrSignature: 'DEFAULT_ANVIL_PRIVATE_KEY'
  ): TypedContractMethod<[], [bigint], 'view'>
  getFunction(
    nameOrSignature: 'IS_SCRIPT'
  ): TypedContractMethod<[], [boolean], 'view'>
  getFunction(
    nameOrSignature: 'deployerKey'
  ): TypedContractMethod<[], [bigint], 'view'>
  getFunction(
    nameOrSignature: 'run'
  ): TypedContractMethod<[], [string], 'nonpayable'>
  getFunction(
    nameOrSignature: 'svgToImageURI'
  ): TypedContractMethod<[svg: string], [string], 'view'>

  filters: {}
}
