import { RouterManifest } from '@/lib/types'

export const manifest: RouterManifest = {
  name: 'OpenAI',
  category: 'router',
  items: [
    {
      id: 'lrYCKF8',
      provider: 'LlamaIndex',
      model: 'gpt-4-turbo-2024-04-09',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      lmsys: {
        rank: 1,
        elo: 1257,
        ci: '+4/-3',
        votes: 30562,
        license: 'Proprietary',
        knowledgeCutoff: '2023/12',
      },
      costPerMTok: { input: 3, output: 4 },
    },
    {
      id: '8ae1xw9',
      provider: 'LlamaIndex',
      model: 'gpt-3.5-turbo-16k-0613',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      costPerMTok: { input: 3, output: 4 },
    },
    {
      id: 'MBMe15Y',
      provider: 'LlamaIndex',
      model: 'gpt-4-1106-vision-preview',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      costPerMTok: { input: 10, output: 30 },
    },
    {
      id: 'jwK7s46',
      model: 'gpt-4-turbo',
      provider: 'LlamaIndex',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      costPerMTok: { input: 10, output: 30 },
    },
    {
      id: 'gpt-4-0125-preview',
      provider: 'LlamaIndex',
      model: 'gpt-4-0125-preview',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      costPerMTok: { input: 10, output: 30 },
    },
    {
      id: 'AwGG3mw',
      model: 'gpt-3.5-turbo-0301',
      provider: 'LlamaIndex',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      costPerMTok: { input: 1.5, output: 2 },
    },
    {
      id: 'gEh0DFS',
      provider: 'LlamaIndex',
      model: 'gpt-3.5-turbo-0613',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      costPerMTok: { input: 1.5, output: 2 },
    },
    {
      id: '6vXmKOs',
      provider: 'LlamaIndex',
      model: 'gpt-3.5-turbo-1106',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      costPerMTok: { input: 1, output: 2 },
    },
    {
      id: 'vG3sqn2',
      model: 'gpt-4',
      provider: 'LlamaIndex',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      costPerMTok: { input: 30, output: 60 },
    },
    {
      id: 'b8ljjRH',
      model: 'gpt-4-1106-preview',
      provider: 'LlamaIndex',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      lmsys: {
        rank: 1,
        elo: 1257,
        ci: '+4/-3',
        votes: 30562,
        license: 'Proprietary',
        knowledgeCutoff: '2023/12',
      },
      costPerMTok: { input: 10, output: 30 },
    },
    {
      id: 'za71xba',
      provider: 'LlamaIndex',
      model: 'gpt-4o',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools', 'agent'],
      lmsys: {
        rank: 1000,
        elo: 1289,
        ci: '+4/-2',
        votes: 12808,
        license: 'Proprietary',
        knowledgeCutoff: '2023/10',
      },
      costPerMTok: { input: 5, output: 15 },
    },
    {
      id: 'EUoAn6w',
      model: 'gpt-3.5-turbo-0125',
      provider: 'LlamaIndex',
      description: '',
      vendor: 'OpenAI',
      skills: ['chat', 'rag', 'tools'],
      costPerMTok: { input: 0.5, output: 1.5 },
    },
  ],
}
