/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers'
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../common'

export interface ToggleDynamicNftInterface extends Interface {
  getFunction(
    nameOrSignature: 'IS_SCRIPT' | 'TOKEN_ID_TO_TOGGLE' | 'run' | 'toggleNft'
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'IS_SCRIPT', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'TOKEN_ID_TO_TOGGLE',
    values?: undefined
  ): string
  encodeFunctionData(functionFragment: 'run', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'toggleNft',
    values: [AddressLike]
  ): string

  decodeFunctionResult(functionFragment: 'IS_SCRIPT', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'TOKEN_ID_TO_TOGGLE',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'run', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'toggleNft', data: BytesLike): Result
}

export interface ToggleDynamicNft extends BaseContract {
  connect(runner?: ContractRunner | null): ToggleDynamicNft
  waitForDeployment(): Promise<this>

  interface: ToggleDynamicNftInterface

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>

  IS_SCRIPT: TypedContractMethod<[], [boolean], 'view'>

  TOKEN_ID_TO_TOGGLE: TypedContractMethod<[], [bigint], 'view'>

  run: TypedContractMethod<[], [void], 'nonpayable'>

  toggleNft: TypedContractMethod<
    [dynamicNftAddress: AddressLike],
    [void],
    'nonpayable'
  >

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T

  getFunction(
    nameOrSignature: 'IS_SCRIPT'
  ): TypedContractMethod<[], [boolean], 'view'>
  getFunction(
    nameOrSignature: 'TOKEN_ID_TO_TOGGLE'
  ): TypedContractMethod<[], [bigint], 'view'>
  getFunction(
    nameOrSignature: 'run'
  ): TypedContractMethod<[], [void], 'nonpayable'>
  getFunction(
    nameOrSignature: 'toggleNft'
  ): TypedContractMethod<[dynamicNftAddress: AddressLike], [void], 'nonpayable'>

  filters: {}
}
